import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import AuthProvider from "@/components/Auth/AuthProvider";
import AuthGuard from "@/components/Auth/AuthGuard";
import Header from "@/components/Header";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <AuthProvider>
            <AuthGuard>
              <div className="flex h-screen">
                <div className="min-h-screen min-w-[250px] p-6">
                  <h1 className="text-2xl">투스카이</h1>
                </div>
                <Separator orientation="vertical" />
                <div className="flex flex-col min-w-[calc(100vw-250px)]">
                  <Header />
                  <Separator orientation="horizontal" />
                  {children}
                </div>
              </div>
            </AuthGuard>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
